CREATE TABLE IF NOT EXISTS category
(
    id           serial      not null,
    name         varchar(60) not null,
    display_name varchar(100),
    CONSTRAINT category_pkey PRIMARY KEY (id),
    CONSTRAINT category_name_key UNIQUE (name)
);

INSERT INTO category (name, display_name)
SELECT *
FROM (VALUES ('groceries', 'Groceries'),
             ('bar', 'Bar, coffee'),
             ('restaurant', 'Restaurant, fast-food'),
             ('online_shopping', 'Online Shopping'),
             ('pets', 'Pets'),
             ('jewelry', 'Jewelry, accessories'),
             ('gifts', 'Gifts'),
             ('electronics', 'Electronics, accessories'),
             ('children', 'Children'),
             ('home', 'Home, Garden'),
             ('stationery', 'Stationery'),
             ('pharmacy', 'Pharmacy, convenience store'),
             ('health_beauty', 'Health and Beauty'),
             ('leisure', 'Leisure'),
             ('clothing', 'Clothing & Shoes'),
             ('housing', 'Housing'),
             ('property', 'Property insurance'),
             ('utilities', 'Utilities, public services'),
             ('maintenance', 'Maintenance, repairs'),
             ('rent', 'Rent'),
             ('mortgage', 'Mortgage'),
             ('services', 'Services'),
             ('transportation', 'Transportation'),
             ('long_distance', 'Long-distance'),
             ('taxi', 'Taxi'),
             ('public_transportation', 'Public transportation'),
             ('business_trips', 'Business trips'),
             ('vehicle', 'Vehicle'),
             ('vehicle_insurance', 'Vehicle insurance'),
             ('fuel', 'Fuel'),
             ('vehicle_maintenance', 'Vehicle maintenance'),
             ('rental', 'Rental'),
             ('rentals', 'Rentals'),
             ('parking', 'Parking'),
             ('alcohol', 'Alcohol, tobacco'),
             ('wellness', 'Wellness, beauty'),
             ('culture', 'Culture, sports events'),
             ('education', 'Education, development'),
             ('life_events', 'Life events'),
             ('books', 'Books'),
             ('charity', 'Charity'),
             ('health', 'Health'),
             ('healthcare', 'Healthcare, doctor'),
             ('sports', 'Sports, fitness'),
             ('tv', 'TV, streaming'),
             ('vacations', 'Vacations, travel, hotels'),
             ('multimedia', 'Multimedia, Computer'),
             ('internet', 'Internet'),
             ('software', 'Software, applications, games'),
             ('postal_services', 'Postal services'),
             ('phone', 'Phone, mobile phone'),
             ('family_allowances', 'Family allowances'),
             ('fines', 'Fines'),
             ('insurance', 'Insurance'),
             ('warnings', 'Warnings'),
             ('charges', 'Charges, fees'),
             ('loan_interest', 'Loan, interest'),
             ('taxes', 'Taxes'),
             ('investments', 'Investments'),
             ('real_estate', 'Real estate'),
             ('collections', 'Collections'),
             ('savings', 'Savings'),
             ('financial_investments', 'Financial investments'),
             ('vehicles', 'Vehicles, personal property'),
             ('income', 'Income'),
             ('checks', 'Checks, vouchers'),
             ('contributions', 'Contributions, subsidies'),
             ('interest', 'Interest, dividends'),
             ('lottery', 'Lottery, gambling'),
             ('loan_rental', 'Loan, rental'),
             ('reimbursements', 'Reimbursements (tax, purchase)'),
             ('rental_income', 'Rental income'),
             ('salaries', 'Salaries'),
             ('invoices', 'Invoices'),
             ('sale', 'Sale'),
             ('others', 'Others'),
             ('missing', 'Missing'),
             ('unknown_expense', 'Unknown expense'),
             ('unknown_entry', 'Unknown entry')) as new_category
WHERE NOT EXISTS (SELECT 1 FROM category where category.name = new_category.column1);
